spring:
  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
    username: sabintarba
    password: sabintarba
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8080